### ISSUE TITLE
Images are sometime shuffled

### ISSUE THREAD

**Issue by OshidaBCF** [jlplenio/imgur-direct-links#16]
Sometime when i get the links, it's not in the proper order, it follow for one or two images then goes completely, i saw this happen on others imgur tools, it is an API problem ?

**Comment by jlplenio** [comment]
Thank you for reporting feedback on this tool. Can you provide a gallery link where the order is incorrect?

**Comment by OshidaBCF** [comment]
sorry, i noticed afterward that it was Imgur that sometime uploaded in the wrong order, i found a way to make it more likely to upload correctly

Sorry )
