### ISSUE TITLE
Add another formatting style - suggestion for improvement 

### ISSUE THREAD

**Issue by ten-typek** [jlplenio/imgur-direct-links#17]
Hi, 
I use this tool to paste the image urls into Excel, into different Cells (in Excel tab Data > Text to Row). For this to work, I must reformat the images in different Editor (for example in Sublime Text, I must convert the urls into one big row: Ctrl+H > Find: \n > Replace: " " (one space). After this I can paste it into Excel and use Text to Row function, with "one space" separator setting). So maybe this could be built-in into the website? :) 

I already bought you a coffee today, but let me thank you once again for this great tool, which saves me a lot of time! ;)

**Comment by jlplenio** [comment]
Is this what you are looking for?

![EXCEL_K4zdvnQIsc](https://github.com/jlplenio/imgur-direct-links/assets/16845311/aa6e2092-a383-4319-8fd4-cf232df14d20)

**Comment by ten-typek** [comment]
Yes, it is! _I didn't know I can make it even in Excel, without using another tool like Sublime.. :D_

**Comment by jlplenio** [comment]
Enjoy the magic of Excel 🪄
